source 'https://github.com/CocoaPods/Specs.git'

target 'ASRManager', :exclusive => true do
  pod "ASRManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ASRManager", :path => "../"

  
end
